title: labsecurity
description: labsecurity is a framework and its use is for ethical hacking and computer security
author:
  name: Dylan Meca
  email: 
show_downloads: false
google_analytics: G-588R86TJDG
comments: true
show_excerpts: false

theme: jekyll-theme-cayman

copyright: "dylan14567"

disqus:
  shortname: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag

